### ISSUE TITLE
OS X

### ISSUE THREAD

**Issue by toffebjorkskog** [generoi/dotfiles#1]
Have you tried it on your mac yet?

**Comment by oxyc** [comment]
Did a quick manual review. There's one critical issue in the bootstrap script (i think): https://github.com/generoi/dotfiles/blob/master/bootstrap.sh#L11

`readlink -f`does not exist in osx readlink version, but if coreutils is installed and greadlink renamed to readlink, it should work. I can look into a fix which doesnt require `readlink -f`.

Other minor issues that do not work:
`meminfo` https://github.com/generoi/dotfiles/blob/master/.bash/aliases.sh#L77
outdated `GREP_OPTIONS` variable https://github.com/generoi/dotfiles/blob/master/.bash/exports.sh#L4
`glgithub` looks like it uses the gnu awk https://github.com/generoi/dotfiles/blob/master/.bash/functions.sh#L63:L73

**Comment by oxyc** [comment]
Also you can use a dry run to test first (check that the output looks sane) `bootstrap.sh --dry`
